### ISSUE TITLE
Exception when assigning cost for "(Empty)" chip

### ISSUE THREAD

**Issue by hieuv** [CensoredUsername/Nier-Automata-editor#4]
(Accidentally) setting a non 0 cost for an "(Empty)" chip slot results in the following log:
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Hieu\AppData\Local\Programs\Python\Python36-32\lib\tkinter\__init__.py", line 1699, in __call__
    return self.func(*args)
  File "C:\Users\Hieu\Downloads\Nier-Automata-editor-master\chips_UI.py", line 67, in <lambda>
    size_cb.bind("<<ComboboxSelected>>", lambda e, args=data: self.on_size_cb_selected(e, args))
  File "C:\Users\Hieu\Downloads\Nier-Automata-editor-master\chips_UI.py", line 83, in on_size_cb_selected
    record = chips.ChipsRecord.from_name(args[1].get())
  File "C:\Users\Hieu\Downloads\Nier-Automata-editor-master\chips.py", line 147, in from_name
    record = struct.unpack("<5i", bs)
struct.error: unpack requires a bytes object of length 20
```
The program still works despite showing this log, however.

**Comment by CensoredUsername** [comment]
Should be fixed now, I disabled changing the cost of (empty) slots
